Algoritmo "07_ZOOLOGICO"
// Disciplina   : Lógica de Programação e Algoritmos
// Professor   : MSc. Tiago Antonio da Silva 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lucas Gabriel de Paula Pinto
// Data atual  : 19/05/2025
Var
// Seção de Declarações das variáveis 
animais: vetor[1..3, 1..5] de caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 




Fimalgoritmo